### ISSUE TITLE
Test trained model

### ISSUE THREAD

**Issue by Sm00thiee** [Sm00thiee/Face-and-object-recogintion#1]
The model seems out-of-date. The machine still can't recognize new models of fans or toothbrush.
@TranMinhNhat-bi9179 could you please test all of objects listed in yolov3.txt?

**Comment by TranMinhNhat-bi9179** [comment]
Newest model of these OBJ doesn't work
-couch 
-chair(must have 4 legs to work)
-dining table 
-t v 
-digital clock (recognized as cellphone)
-hairdryer
